baseURL = "https://sevenkieran.github.io/"
languageCode = "en-us"
title = "Kieran Seven"

theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
author = "Kieran Seven"
favicon = "images/Logo.svg"
site_logo = ""
description = ""
background_color_class = "bg-near-black"
recent_posts_number = 3
text_color = "white-80"


[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 10