baseURL = "https://sevenkieran.github.io/"
languageCode = "en-us"
title = "Kieran Seven"

theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
author = "Kieran Seven"
favicon = "images/Logo.svg"
site_logo = ""
description = ""
background_color_class = "bg-near-black"
recent_posts_number = 3
text_color = ""


[params.ananke.social.follow]
networks = [
  'github',
  'linkedin'
]

[params.ananke.social.github]
username = 'sevenkieran'

[params.ananke.social.linkedin]
username = 'kieran-seven-137387275'